server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    username: root
    password: Long050720
    url: jdbc:mysql://120.24.88.212:3306/aurora?useSSL=true&userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

site:
  filePath: /home/AuroraWebSite/uploads
  public-host: 120.24.88.212:8081

